import { destinationSentiment, quarterlySentiment, stakeholderLabel, topNegativeAspects } from '../data/sentiment';

const score=value=>Number.isFinite(value)?`${value>0?'+':''}${value.toFixed(1)}`:'N/A';
const pillarValue=(pillars,key)=>Number.isFinite(pillars?.pillars?.[key])?`${pillars.pillars[key].toFixed(1)} / 100`:'N/A';

export default function StateSentimentPanel({ state, pillars, destinationRows, aspects, quarterly }) {
 const result=destinationSentiment(destinationRows,state), trend=quarterlySentiment(quarterly), coverage=trend.length?`${trend[0].period}–${trend.at(-1).period}`:'N/A', issues=topNegativeAspects(aspects);
 return <section className="state-sentiment"><div className="pillar-heading"><div><span className="eyebrow">PUBLIC SENTIMENT</span><h3>Measured conditions and public perception</h3></div><span className="muted">Pooled comments · dated coverage {coverage}</span></div><p className="muted">Sentiment is separate from STI, uses a −100 to +100 net scale, and is not filtered by the selected STI year.</p><div className="state-sentiment-grid"><div><h3>Sentiment by dimension{result.destination&&<span className="sentiment-source">Source destination: {result.destination}</span>}</h3>{result.rows.length?<div className="dimension-comparison">{result.rows.map(row=><article key={row.sustainability_dimension}><span>{stakeholderLabel(row.sustainability_dimension)}</span><strong>{score(row.net_sentiment)}</strong><small>Public sentiment · n={Number.isFinite(row.n)?row.n.toLocaleString('en-MY'):'N/A'}</small>{row.sustainability_dimension==='infrastructure'?<em>Not an STI pillar</em>:<em>Measured pillar · {pillarValue(pillars,row.sustainability_dimension)}</em>}</article>)}</div>:<div className="empty">No sufficient destination sentiment data is available for {state}.</div>}</div><div><h3>Top negative issues <span className="sentiment-source">National comment corpus</span></h3>{issues.length?<ol className="aspect-list">{issues.map(row=><li key={row.tourism_aspect}><div><strong>{stakeholderLabel(row.tourism_aspect)}</strong><small>n={row.n.toLocaleString('en-MY')}</small></div><span>{row.negative_pct.toFixed(1)}% negative<small>Net {score(row.net_sentiment)}</small></span></li>)}</ol>:<div className="empty">Aspect sentiment is unavailable.</div>}</div></div><p className="chart-note">Destination sentiment and measured pillars can be compared as separate signals; alignment does not establish causation. Destination aggregates provide sample counts but no low-sample flag. Aspect rankings are national because that export has no destination field; its exported low-sample rows are excluded.</p></section>;
}
