import { destinationSentiment, quarterlySentiment, stakeholderLabel } from '../data/sentiment';

const score=value=>Number.isFinite(value)?`${value>0?'+':''}${value.toFixed(1)}`:'N/A';
const pillarValue=(pillars,key)=>Number.isFinite(pillars?.pillars?.[key])?`${pillars.pillars[key].toFixed(1)} / 100`:'N/A';
const sentimentBand=value=>{ if(!Number.isFinite(value)) return null; if(value>=25) return ['Positive','positive']; if(value>=5) return ['Slightly positive','slightly-positive']; if(value>-5) return ['Neutral','neutral']; if(value>-25) return ['Slightly negative','slightly-negative']; return ['Negative','negative']; };
const SentimentScore=({value})=>{ const band=sentimentBand(value); return <div className="sentiment-score-line"><strong>{score(value)}</strong>{band&&<span className={`sentiment-band ${band[1]}`}>{band[0]}</span>}</div>; };

export default function StateSentimentPanel({ state, pillars, destinationRows, aspects, quarterly }) {
 const result=destinationSentiment(destinationRows,state), trend=quarterlySentiment(quarterly), coverage=trend.length?`${trend[0].period}–${trend.at(-1).period}`:'N/A';
 return <section className="state-sentiment"><div className="pillar-heading"><div><span className="eyebrow">STATE PUBLIC SENTIMENT</span><h3>{state} sentiment analysis</h3></div><span className="muted">Pooled comments · dated coverage {coverage}</span></div><p className="muted">Sentiment is separate from STI, uses a −100 to +100 net scale, and is not filtered by the selected STI year.</p><div className="state-sentiment-grid state-sentiment-single"><div><h3>Sentiment by sustainability dimension{result.destination&&<span className="sentiment-source">Destination signal: {result.destination}</span>}</h3>{result.rows.length?<div className="dimension-comparison">{result.rows.map(row=><article key={row.sustainability_dimension}><span>{stakeholderLabel(row.sustainability_dimension)}</span><SentimentScore value={row.net_sentiment}/><small>Public sentiment · n={Number.isFinite(row.n)?row.n.toLocaleString('en-MY'):'N/A'}</small>{row.sustainability_dimension==='infrastructure'?<em>Not an STI pillar</em>:<em>Measured pillar · {pillarValue(pillars,row.sustainability_dimension)}</em>}</article>)}</div>:<div className="empty">No sufficient destination sentiment data is available for {state}.</div>}<p className="sentiment-band-note">Interpretation bands: ≥ +25 Positive · +5 to &lt; +25 Slightly positive · −5 to &lt; +5 Neutral · −25 to ≤ −5 Slightly negative · &lt; −25 Negative.</p></div></div><p className="chart-note">Destination sentiment and measured pillars can be compared as separate signals; alignment does not establish causation. Destination aggregates provide sample counts but no low-sample flag. National issue rankings are shown on the Overview page.</p></section>;
}
