import assert from 'node:assert/strict';
import fs from 'node:fs';
import { geoState } from '../src/data/geoNameMap.js';
import { parseCsv } from '../src/data/csv.js';
import { getPillarBreakdown, getStiAvailability, getStiSnapshot } from '../src/data/stiAvailability.js';
import { getOverviewKpis } from '../src/data/overviewKpis.js';
import { getYoyReport } from '../src/data/yoyReport.js';
import { getRecoveryInsights } from '../src/data/recoveryInsights.js';
import { destinationSentiment, quarterlySentiment, sentimentMetrics, topNegativeAspects } from '../src/data/sentiment.js';
const read=name=>JSON.parse(fs.readFileSync(`public/data/${name}.json`,'utf8'));
const state=read('state_year'), sti=read('sustainability_index'), national=read('national_year');
assert.equal(state.length,176);assert.equal(sti.length,65);assert.equal(national.length,14);
for(const rows of [state,sti,national])assert.equal(new Set(rows.map(r=>`${r.state??'national'}:${r.year}`)).size,rows.length);
const names=new Set(state.map(r=>r.state));assert.equal(names.size,16);
for(const rows of [state,sti,national])for(const row of rows)for(const value of Object.values(row))if(typeof value==='number')assert(Number.isFinite(value));
for(const row of state.filter(r=>r.year===2025))assert.equal(row.coastalGoodExcellentPct,null);
for(const row of sti){assert(row.stiScore>=0&&row.stiScore<=100);assert.equal(typeof row.PC3_Standardized,'number');}
for(const [state,score] of Object.entries(read('map_scores')))assert.equal(Math.round(sti.find(r=>r.year===2024&&r.state===state).stiScore),score);
const geo=JSON.parse(fs.readFileSync('public/data/malaysia-states.geojson'));
assert.equal(geo.features.length,16);assert.deepEqual(new Set(geo.features.map(geoState)),names);
assert.equal(read('causal_findings').length,3);
const details=parseCsv(fs.readFileSync('public/data/agg_states_detail.csv','utf8'));
const fallbacks=parseCsv(fs.readFileSync('public/data/agg_states_fallback.csv','utf8'));
assert.deepEqual(getStiAvailability(details,fallbacks,'Melaka',2024),{status:'full',value:100,label:'STI',message:null});
assert.equal(getStiAvailability(details,fallbacks,'Melaka',2025).status,'fallback');
assert.deepEqual(getStiAvailability(details,fallbacks,'Perlis',2024),{status:'fallback',value:37.94314501370387,label:'Economic + Social',message:'Full STI unavailable — no coastal water-quality monitoring stations.'});
assert.deepEqual(getStiAvailability(details,fallbacks,'Johor',2016),{status:'unavailable',value:null,label:null,message:'Full STI: Not calculated for this year/state.'});
const overview=read('agg_overview');
const overviewKpis=getOverviewKpis(details,overview);
assert.equal(overviewKpis.latestYear,2024);
assert.equal(overviewKpis.covered,13);
assert.equal(overviewKpis.total,16);
assert(Math.abs(overviewKpis.averageSti-81.41568332164928)<1e-12);
assert.equal(overviewKpis.deltaEconomic,-2.5);
assert.equal(overviewKpis.deltaEnvironmental,2.7);
const canonicalStates=[...new Set(state.map(row=>row.state))];
const ranking2024=getStiSnapshot(details,fallbacks,canonicalStates,2024).filter(row=>row.status==='full').sort((a,b)=>b.value-a.value);
assert.equal(ranking2024.length,13);
assert.deepEqual(ranking2024.slice(0,2).map(row=>row.state),['Melaka','Pulau Pinang']);
assert.equal(ranking2024.at(-1).state,'W.P. Labuan');
for(const name of ['Johor','Selangor','Sabah','Sarawak'])assert.equal(ranking2024.find(row=>row.state===name).value,details.find(row=>row.State===name&&row.Year===2024).STI);
for(const name of ['Perlis','W.P. Kuala Lumpur','W.P. Putrajaya'])assert.notEqual(getStiAvailability(details,fallbacks,name,2024).status,'full');
for(const year of [2015,2016,2025])assert.equal(getStiSnapshot(details,fallbacks,canonicalStates,year).filter(row=>row.status==='full').length,0);
assert.equal(new Set(details.map(row=>`${row.State}:${row.Year}`)).size,details.length);
for(const row of details)for(const key of ['Economic_0_100','Social_0_100','Environmental_0_100'])assert(Number.isFinite(row[key])&&row[key]>=0&&row[key]<=100);
for(const name of ['Johor','Selangor','Sabah','Sarawak'])assert(Object.values(getPillarBreakdown(details,fallbacks,name,2024).pillars).every(Number.isFinite));
for(const name of ['Perlis','W.P. Kuala Lumpur','W.P. Putrajaya'])assert.deepEqual(getPillarBreakdown(details,fallbacks,name,2024).pillars,{economic:null,social:null,environmental:null});
for(const year of [2015,2016,2025])assert.equal(getPillarBreakdown(details,fallbacks,'Johor',year).pillars.environmental,null);
for(const file of ['agg_states_detail.csv','agg_states_fallback.csv'])assert.equal(fs.readFileSync(`dashboard_exports_other/${file}`,'utf8'),fs.readFileSync(`public/data/${file}`,'utf8'));
assert.equal(fs.readFileSync('dashboard_exports_other/agg_overview.json','utf8'),fs.readFileSync('public/data/agg_overview.json','utf8'));
const yoy=parseCsv(fs.readFileSync('public/data/agg_states_yoy_values.csv','utf8'));
assert.equal(yoy.length,1760);
assert.equal(new Set(yoy.map(row=>`${row.State}:${row.Year}:${row.indicator}`)).size,yoy.length);
assert.equal(new Set(yoy.filter(row=>row.part_of_sti==='True').map(row=>row.indicator)).size,6);
assert(yoy.filter(row=>row.part_of_sti==='False').every(row=>row.higher_is_better==null));
const johor2024=getYoyReport(yoy,'Johor',2024);
assert.equal(johor2024.length,10);
assert.equal(johor2024.find(row=>row.indicator==='Unemployment Rate (%)').status,'Favourable');
assert.equal(johor2024.find(row=>row.indicator==='Non-Domestic Water Share (%)').status,'Concern');
assert(getYoyReport(yoy,'Perlis',2024).some(row=>row.partOfSti&&row.currentValue!=null));
assert.equal(getYoyReport(yoy,'Johor',2015).filter(row=>row.change!=null).length,0);
assert.equal(fs.readFileSync('dashboard_exports_other/agg_states_yoy_values.csv','utf8'),fs.readFileSync('public/data/agg_states_yoy_values.csv','utf8'));
const recovery=parseCsv(fs.readFileSync('public/data/agg_states_recovery.csv','utf8'));
const quadrants=new Set(['Sustainable improvement','Growth under environmental stress','Environmental recovery, tourism weakness','Overall deterioration']);
assert.equal(recovery.length,13);
assert(recovery.every(row=>quadrants.has(row.Quadrant)&&Number.isFinite(row.Delta_Economic)&&Number.isFinite(row.Delta_Environmental)));
assert(details.every(row=>Number.isFinite(row.STI_Stability_Score_0_100)&&row.STI_Stability_Score_0_100>=0&&row.STI_Stability_Score_0_100<=100));
assert.deepEqual(getRecoveryInsights(details,recovery,'Johor'),{quadrant:'Environmental recovery, tourism weakness',deltaEconomic:-5,deltaEnvironmental:6.5,stability:83.5});
for(const name of ['Perlis','W.P. Kuala Lumpur','W.P. Putrajaya'])assert.deepEqual(getRecoveryInsights(details,recovery,name),{quadrant:null,deltaEconomic:null,deltaEnvironmental:null,stability:null});
assert.equal(fs.readFileSync('dashboard_exports_other/agg_states_recovery.csv','utf8'),fs.readFileSync('public/data/agg_states_recovery.csv','utf8'));
const sentimentOverall=parseCsv(fs.readFileSync('public/data/agg_sentiment_overall.csv','utf8'));
const sentimentDimensions=parseCsv(fs.readFileSync('public/data/agg_sentiment_dimension.csv','utf8'));
const sentimentStakeholders=parseCsv(fs.readFileSync('public/data/agg_sentiment_stakeholder.csv','utf8'));
const sentimentQuarterly=parseCsv(fs.readFileSync('public/data/agg_sentiment_quarterly.csv','utf8'));
const sentiment=sentimentMetrics(sentimentOverall), quarterly=quarterlySentiment(sentimentQuarterly);
assert.equal(sentiment.analyzed_comments,4755);
assert(Math.abs(sentiment.positive_pct+sentiment.neutral_pct+sentiment.negative_pct-100)<0.11);
for(const row of sentimentDimensions){assert(row.sustainability_dimension);assert(row.n>=0);assert(Math.abs(row.positive_pct+row.neutral_pct+row.negative_pct-100)<0.11);assert(row.net_sentiment>=-100&&row.net_sentiment<=100);}
for(const row of sentimentStakeholders){assert(row.stakeholder);assert(row.n>=0);assert(Math.abs(row.positive_pct+row.neutral_pct+row.negative_pct-100)<0.11);assert(row.net_sentiment>=-100&&row.net_sentiment<=100);}
assert.equal(quarterly[0].period,'2020Q4');assert.equal(quarterly.at(-1).period,'2026Q3');
assert(!quarterly.some(row=>row.period==='NaT'));
for(const [source,target] of [['agg_overall.csv','agg_sentiment_overall.csv'],['agg_dimension.csv','agg_sentiment_dimension.csv'],['agg_stakeholder.csv','agg_sentiment_stakeholder.csv'],['agg_timeseries_quarterly.csv','agg_sentiment_quarterly.csv']])assert.equal(fs.readFileSync(`dashboard_exports/${source}`,'utf8'),fs.readFileSync(`public/data/${target}`,'utf8'));
const destinationDimensions=parseCsv(fs.readFileSync('public/data/agg_sentiment_destination_dimension.csv','utf8'));
const sentimentAspects=parseCsv(fs.readFileSync('public/data/agg_sentiment_aspect.csv','utf8'));
assert.equal(destinationDimensions.length,48);
assert.equal(new Set(destinationDimensions.map(row=>`${row.destination}:${row.sustainability_dimension}`)).size,destinationDimensions.length);
assert(destinationDimensions.every(row=>row.destination&&row.sustainability_dimension&&row.n>=0&&row.net_sentiment>=-100&&row.net_sentiment<=100));
assert.equal(destinationSentiment(destinationDimensions,'Pulau Pinang').destination,'Penang');
assert.equal(destinationSentiment(destinationDimensions,'W.P. Kuala Lumpur').destination,'Kuala Lumpur');
assert.equal(destinationSentiment(destinationDimensions,'W.P. Putrajaya').destination,'Putrajaya');
assert.equal(destinationSentiment(destinationDimensions,'Kedah').destination,'Langkawi');
assert.equal(destinationSentiment(destinationDimensions,'Selangor').rows.length,0);
assert(sentimentAspects.every(row=>row.tourism_aspect&&row.n>=0&&row.net_sentiment>=-100&&row.net_sentiment<=100));
assert.deepEqual(topNegativeAspects(sentimentAspects).map(row=>row.tourism_aspect),['cleanliness','facilities','safety','accessibility','hospitality']);
assert(!topNegativeAspects(sentimentAspects,16).some(row=>row.low_sample_warning==='True'));
for(const [source,target] of [['agg_destination_dimension.csv','agg_sentiment_destination_dimension.csv'],['agg_aspect.csv','agg_sentiment_aspect.csv']])assert.equal(fs.readFileSync(`dashboard_exports/${source}`,'utf8'),fs.readFileSync(`public/data/${target}`,'utf8'));
const forecastTasks=parseCsv(fs.readFileSync('public/data/agg_forecast_national_dashboard.csv','utf8'));
const forecastVisitors=parseCsv(fs.readFileSync('public/data/agg_forecast_states_visitors_dashboard.csv','utf8'));
assert.deepEqual(forecastTasks.map(row=>row.task),['domestic_visitors','water_pressure','coastal_quality']);
assert.equal(forecastVisitors.length,16);
assert.equal(new Set(forecastVisitors.map(row=>row.state)).size,16);
assert(forecastVisitors.every(row=>Number.isFinite(row.actual_2024)&&Number.isFinite(row.model_forecast_2025)&&Number.isFinite(row.actual_2025)));
for(const row of forecastTasks){
 assert(Number.isFinite(row.actual_2024)&&Number.isFinite(row.model_forecast_2025)&&Number.isFinite(row.naive_error)&&Number.isFinite(row.model_error));
 assert.equal(row.beats_baseline==='True',row.model_error<row.naive_error);
}
const visitorForecast=forecastTasks.find(row=>row.task==='domestic_visitors');
assert.equal(visitorForecast.actual_2025,forecastVisitors.reduce((sum,row)=>sum+row.actual_2025,0));
assert.deepEqual([visitorForecast.naive_error_metric,visitorForecast.naive_error,visitorForecast.model_error_metric,visitorForecast.model_error],['MAPE_%',15.7,'MAPE_%',10.6]);
for(const task of ['water_pressure','coastal_quality'])assert.equal(forecastTasks.find(row=>row.task===task).actual_2025,null);
assert.equal(fs.readFileSync('dashboard_exports_other/agg_forecast_national_dashboard.csv','utf8'),fs.readFileSync('public/data/agg_forecast_national_dashboard.csv','utf8'));
assert.equal(fs.readFileSync('dashboard_exports_other/agg_forecast_states_visitors_dashboard.csv','utf8'),fs.readFileSync('public/data/agg_forecast_states_visitors_dashboard.csv','utf8'));
console.log('PASS: export counts, keys, nulls, v5 forecast tasks, STI fallback states, all 16 boundaries and static file hand-off.');
