import { useState } from 'react';
import { useDashboardData } from './hooks/useDashboardData';
import Header from './components/Header';
import KpiCards from './components/KpiCards';
import StateExplorer from './components/StateExplorer';
import NationalTrends from './components/NationalTrends';
import ForecastPanel from './components/ForecastPanel';
import CausalInsights from './components/CausalInsights';
import Methodology from './components/Methodology';
import OverviewSentiment from './components/OverviewSentiment';
export default function App() {
 const {data,error,loading}=useDashboardData();
 const [tab,setTab]=useState('Overview'),[range,setRange]=useState([2012,2025]),[selection,setSelection]=useState(null),[selectedState,setSelectedState]=useState('Melaka');
 if(loading)return <main className="loading" role="status"><span className="brand-mark">◈</span><h1>Loading the observatory</h1><p>Reading local notebook exports…</p></main>;
 if(error)return <main className="loading" role="alert"><h1>Data could not be loaded</h1><p>{error.message}</p><p>Run the data exporter and serve the site with Vite.</p><button className="button" onClick={()=>location.reload()}>Retry</button></main>;
 const allStates=[...new Set(data.state_year.map(r=>r.state))].sort(), states=selection??allStates;
 const toggle=state=>{const next=states.includes(state)?states.filter(s=>s!==state):[...states,state];setSelection(next);if(!next.includes(selectedState))setSelectedState(next[0]??'');};
 return <><Header metadata={data.metadata} tab={tab} setTab={setTab}/><main className="page"><div className="hero"><div><span className="eyebrow">SUSTAINABLE TOURISM / MALAYSIA</span><h1>Growth, with a longer view.</h1><p>Explore how domestic tourism, communities and coastal ecosystems move together.</p></div><a className="button download" href={`${import.meta.env.BASE_URL}data/Data.csv`} download>Download data <span>↗</span></a></div><div className="controls"><div className="range-control"><span className="eyebrow">YEAR RANGE</span><label>From <strong>{range[0]}</strong><input aria-label="Start year" type="range" min="2012" max="2025" value={range[0]} onChange={e=>setRange([+e.target.value,Math.max(+e.target.value,range[1])])}/></label><label>To <strong>{range[1]}</strong><input aria-label="End year" type="range" min="2012" max="2025" value={range[1]} onChange={e=>setRange([Math.min(range[0],+e.target.value),+e.target.value])}/></label></div><details className="state-picker"><summary>{states.length===16?'All 16 states & territories':`${states.length} states selected`} <span>⌄</span></summary><div className="state-options"><div className="selection-actions"><button onClick={()=>{setSelection(null);setSelectedState('Melaka');}}>Select all</button><button onClick={()=>{setSelection([]);setSelectedState('');}}>Clear</button></div>{allStates.map(state=><label key={state}><input type="checkbox" checked={states.includes(state)} onChange={()=>toggle(state)}/>{state}</label>)}</div></details><button className="reset" onClick={()=>{setRange([2012,2025]);setSelection(null);setSelectedState('Melaka');}}>Reset filters ↺</button></div><p className="filter-note">Year range applies to state and national trends. State selection also applies to forecasts. Headline KPIs always show the latest available national or coastal data.</p>{tab!=='States'&&<KpiCards data={data} overview={tab==='Overview'}/>}<div className="content-stack">{tab==='States'&&<StateExplorer data={data} range={range} states={states} selectedState={selectedState} onSelect={setSelectedState}/ >}{tab==='Overview'&&<><NationalTrends data={data} range={range} states={states}/><OverviewSentiment overall={data.sentiment_overall} dimensions={data.sentiment_dimensions} stakeholders={data.sentiment_stakeholders} quarterly={data.sentiment_quarterly}/></>}{tab==='Forecast'&&<ForecastPanel rows={data.forecast.filter(r=>states.includes(r.state))}/ >}{tab==='Causal'&&<CausalInsights findings={data.causal_findings}/ >}{tab==='Methodology'&&<Methodology metadata={data.metadata}/ >}</div><footer><span>TOURISM / MALAYSIA <small>DOSM Datathon 2026</small></span><span>Data vintage: {data.metadata.dataVintage}</span><button onClick={()=>window.print()}>Print this view ↗</button></footer></main></>;
}
